/**
 * Single source of truth for every IPC channel and push-event name.
 *
 * Both the main process (`registerIpcHandler`, `ipcMain.on/emit`,
 * `webContents.send`) and the renderer (`ipcRenderer.invoke/on/send`) are
 * typed against these unions, so a misspelled or unregistered name fails
 * typecheck instead of silently drifting at runtime.
 *
 * NOTE: keep name/value in sync with the actual handlers in
 * `src/main/utils/ipc-*.ts` and the push events in `src/main/core/*`.
 */

/** Every renderer→main `invoke` channel (registered via `registerIpcHandler`). */
type IpcChannel =
  | 'addOverrideItem'
  | 'addProfileItem'
  | 'ageIdentityToRecipient'
  | 'alert'
  | 'applyTheme'
  | 'cancelUpdate'
  | 'changeCurrentProfile'
  | 'checkAutoRun'
  | 'checkCorePermission'
  | 'checkElevateTask'
  | 'checkUpdate'
  | 'clearCachedMihomoLogs'
  | 'closeFloatingWindow'
  | 'closeMainWindow'
  | 'closeTrayIcon'
  | 'copyEnv'
  | 'createHeapSnapshot'
  | 'deleteElevateTask'
  | 'disableAutoRun'
  | 'downloadAndInstallUpdate'
  | 'downloadSubStore'
  | 'enableAutoRun'
  | 'fetchThemes'
  | 'findSystemMihomo'
  | 'generateAgeKeyPair'
  | 'getAppConfig'
  | 'getAppName'
  | 'getCachedMihomoLogs'
  | 'getControledMihomoConfig'
  | 'getCurrentProfileItem'
  | 'getCurrentProfileStr'
  | 'getFilePath'
  | 'getFilePreviewStr'
  | 'getFileStr'
  | 'getGistUrl'
  | 'getIconDataURL'
  | 'getImageDataURL'
  | 'getInterfaces'
  | 'getOverride'
  | 'getOverrideConfig'
  | 'getOverrideItem'
  | 'getOverrideProfileStr'
  | 'getProfileConfig'
  | 'getProfileItem'
  | 'getProfileStr'
  | 'getRawProfileStr'
  | 'getRuntimeConfig'
  | 'getRuntimeConfigStr'
  | 'getUserAgent'
  | 'getVersion'
  | 'importThemes'
  | 'initService'
  | 'installService'
  | 'isAlwaysOnTop'
  | 'listWebdavBackups'
  | 'manualGrantCorePermition'
  | 'mihomoChangeProxy'
  | 'mihomoCloseConnection'
  | 'mihomoCloseConnections'
  | 'mihomoConfig'
  | 'mihomoGroupDelay'
  | 'mihomoGroups'
  | 'mihomoProxies'
  | 'mihomoProxyDelay'
  | 'mihomoProxyProviders'
  | 'mihomoRuleProviders'
  | 'mihomoRules'
  | 'mihomoRulesDisable'
  | 'mihomoUnfixedProxy'
  | 'mihomoUpdateProxyProviders'
  | 'mihomoUpdateRuleProviders'
  | 'mihomoUpgrade'
  | 'mihomoUpgradeGeo'
  | 'mihomoUpgradeUI'
  | 'mihomoVersion'
  | 'notDialogQuit'
  | 'openDevTools'
  | 'openFile'
  | 'openUWPTool'
  | 'patchAppConfig'
  | 'patchControledMihomoConfig'
  | 'patchMihomoConfig'
  | 'platform'
  | 'quitApp'
  | 'quitWithoutCore'
  | 'readImageFileDataURL'
  | 'readTextFile'
  | 'readTheme'
  | 'registerShortcut'
  | 'relaunchApp'
  | 'removeOverrideItem'
  | 'removeProfileItem'
  | 'resetAppConfig'
  | 'resolveThemes'
  | 'restartCore'
  | 'restartMihomoConnections'
  | 'restartMihomoLogs'
  | 'restartService'
  | 'revokeCorePermission'
  | 'saveFileStrWithElevation'
  | 'serviceStatus'
  | 'setAlwaysOnTop'
  | 'setDockVisible'
  | 'setFileStr'
  | 'setNativeTheme'
  | 'setOverride'
  | 'setOverrideConfig'
  | 'setProfileConfig'
  | 'setProfileStr'
  | 'setTitleBarOverlay'
  | 'setupFirewall'
  | 'showContextMenu'
  | 'showFloatingWindow'
  | 'showMainWindow'
  | 'showTrayIcon'
  | 'startMonitor'
  | 'startNetworkDetection'
  | 'startService'
  | 'startSubStoreBackendServer'
  | 'startSubStoreFrontendServer'
  | 'stopCore'
  | 'stopNetworkDetection'
  | 'stopService'
  | 'stopSubStoreBackendServer'
  | 'stopSubStoreFrontendServer'
  | 'subStoreCollections'
  | 'subStoreFrontendPort'
  | 'subStorePort'
  | 'subStoreSubs'
  | 'testServiceConnection'
  | 'triggerMainWindow'
  | 'triggerSysProxy'
  | 'uninstallService'
  | 'updateOverrideItem'
  | 'updateProfileItem'
  | 'updateTrayIcon'
  | 'webdavBackup'
  | 'webdavDelete'
  | 'webdavRestore'
  | 'writeTheme'

/**
 * Every push/notification channel. These flow between `webContents.send`
 * (main→renderer) and `ipcRenderer.on`/`ipcRenderer.send` +
 * `ipcMain.on`/`ipcMain.emit` (renderer↔main one-way events).
 */
type IpcEventName =
  | 'appConfigUpdated'
  | 'app-notification'
  | 'app-notification-dismiss'
  | 'app-notification-ready'
  | 'controledMihomoConfigUpdated'
  | 'core-started'
  | 'core-status-changed'
  | 'core-stopped'
  | 'customTray:close'
  | 'groupsUpdated'
  | 'mihomoConnections'
  | 'mihomoLogs'
  | 'mihomoMemory'
  | 'mihomoTraffic'
  | 'overrideConfigUpdated'
  | 'override-install-confirm-result'
  | 'profileConfigUpdated'
  | 'profile-install-confirm-result'
  | 'quit-confirm-result'
  | 'renderer-content-ready'
  | 'rulesUpdated'
  | 'show-override-install-confirm'
  | 'show-profile-install-confirm'
  | 'show-quit-confirm'
  | 'trayIconUpdate'
  | 'updateFloatingWindow'
  | 'update-status'
  | 'updateTrayMenu'
